=== danganiev/WorldsGame/Code/Worlds/WorldsContent/Skin/skin.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.2.746 (http://www.liquid-technologies.com)-->

<xs:schema elementFormDefault="qualified" id="skin" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--
    targetNamespace="http://tempuri.org/skin.xsd"
    xmlns="http://tempuri.org/skin.xsd"
    xmlns:mstns="http://tempuri.org/skin.xsd"
  -->

  <!-- Complex type for declaring a font used in this skin -->
  <xs:complexType name="fontType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="contentPath" type="xs:string" use="required" />
  </xs:complexType>

  <!-- Complex type for declaring a bitmap used in this skin -->
  <xs:complexType name="bitmapType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="contentPath" type="xs:string" use="required" />
  </xs:complexType>

  <!-- Complex type for the resources bracket -->
  <xs:complexType name="resourcesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="font" type="fontType" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="bitmap" type="bitmapType" />
    </xs:sequence>
  </xs:complexType>

  <!-- Complex type for specifying a bitmap region to draw into the frame -->
  <xs:complexType name="regionType">
    <xs:attribute name="id" type="xs:string" use="optional" />
    <xs:attribute name="source" type="xs:string" use="required" />
    <xs:attribute name="hplacement" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="left" />
          <xs:enumeration value="right" />
          <xs:enumeration value="stretch" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="vplacement" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="top" />
          <xs:enumeration value="bottom" />
          <xs:enumeration value="stretch" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="x" type="xs:int" use="required" />
    <xs:attribute name="y" type="xs:int" use="required" />
    <xs:attribute name="w" type="xs:int" use="required" />
    <xs:attribute name="h" type="xs:int" use="required" />
  </xs:complexType>

  <!-- Complex type for specifying where text is placed in a frame -->
  <xs:complexType name="textType">
    <xs:attribute name="font" type="xs:string" use="required" />
    <xs:attribute name="hplacement" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="left" />
          <xs:enumeration value="right" />
          <xs:enumeration value="center" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="vplacement" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="top" />
          <xs:enumeration value="bottom" />
          <xs:enumeration value="center" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="xoffset" type="xs:int" use="optional" />
    <xs:attribute name="yoffset" type="xs:int" use="optional" />
    <xs:attribute name="color" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- Complex type for specifying a frame, the building block of GUI elements -->
  <xs:complexType name="frameType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="region" type="regionType" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="text" type="textType" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <!-- Complex type for the frames bracket -->
  <xs:complexType name="framesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="frame" type="frameType" />
    </xs:sequence>
  </xs:complexType>

  <!-- Complex type for the root bracket in a skin file -->
  <xs:complexType name="skinType">
    <xs:all minOccurs="1" maxOccurs="1">
      <xs:element minOccurs="1" name="resources" type="resourcesType" />
      <xs:element minOccurs="1" name="frames" type="framesType" />
    </xs:all>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <!-- Root element of an XML skin file -->
  <xs:element name="skin" type="skinType" />
</xs:schema>

=== danganiev/WorldsGame/Code/Worlds/WorldsContent/Skin/Suave/Suave.skin.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--

Important:

The "Suave" theme is based on a Windows XP theme created by Mohsin Naqi.

Graphics were taken unmodified from that theme and put together to
create the "Suave" skin by Markus Ewald (http://www.nuclex.org).

The original artist has agreed to allow for unlimited usage of this theme as
long as he is credited for his art. So if you decide to publish a project
that uses the theme, please give due credit to the original artist!

>
> Hello,
>
> Go ahead and do whatever you want with it, you have my permission :) I only
> want to be credited for the art.
>
> Thank you
> Mohsin
> ~~~~~ Original Message ~~~~~ From: "Markus Ewald" <***spam protection=""***>
> To: "Mohsin Naqi" <***spam protection=""***>
> Sent: Friday, June 23, 2006 9:47 PM
> Subject: Your Suave theme
>
>
> > Hi!
>>
> > I really like your Suave theme because it doesn't look so serious and
> > sterile as most other themes I've seen!
>>
> > I'm working on the CeGui# project
> > (http://ceguisharp.sourceforge.net/index.php/Main_Page),
> > an open source component used to display graphical user interfaces in
> > computer games.
>>
> > Well, the existing themes we have are looking rather dull, so I'm hoping
> > to come up with a new, good looking default theme for the library. Would
> > it be okay with you if I created a CeGui# theme from your Suave theme?
>>
> > Of course all credits for the art go to you. My only requirement is that
> > the CeGui# theme I create needs to be free anyone to use (hobbyists as
> > well as commercial programmers).
>>
> > Do I have your ok?
>>
> > Thanks ahead, ;)
> > -Markus-

-->

<skin
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../skin.xsd"
  name="Suave"
>

  <!--
    Resources used to draw GUI elements using this skin
  -->
  <resources>
    <font name="title" contentPath="TitleFont" />
    <font name="header" contentPath="HeaderFont" />
    <font name="default" contentPath="SuaveDefaultFont" />
    <bitmap name="controls" contentPath="SuaveSheet" />
    <bitmap name="inventory" contentPath="./Inventory/Inventory" />
  </resources>

  <!--
    Frames that are used as building blocks for GUI elements
  -->
  <frames>
      <!--
      Frame used to draw a normal window
    -->
    <frame name="window">
      <region source="controls" hplacement="left" vplacement="top" x="1" y="1" w="5" h="24" />
      <region source="controls" hplacement="stretch" vplacement="top" x="6" y="1" w="32" h="24" />
      <region source="controls" hplacement="right" vplacement="top" x="38" y="1" w="5" h="24" />
      <region source="controls" hplacement="left" vplacement="stretch" x="1" y="25" w="5" h="18" id="border-w" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="6" y="25" w="32" h="18" id="client" />
      <region source="controls" hplacement="right" vplacement="stretch" x="38" y="25" w="5" h="18" id="border-e" />
      <region source="controls" hplacement="left" vplacement="bottom" x="1" y="43" w="5" h="4" id="border-sw" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="6" y="43" w="32" h="4" id="border-s" />
      <region source="controls" hplacement="right" vplacement="bottom" x="38" y="43" w="5" h="4" id="border-se" />
      <text font="title" hplacement="left" vplacement="top" xoffset="8" yoffset="0" color="#ffffff" />
    </frame>
    
    <!--
      Frame used to draw a borderless window
    -->
    <frame name="borderless_window">
      <text font="title" hplacement="left" vplacement="top" xoffset="8" yoffset="0" color="#ffffff" />
    </frame>

    <!--
      Frame used for a label
    -->
    <frame name="label">
      <text font="default" hplacement="left" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <frame name="item_count_label">
      <text font="default" hplacement="left" vplacement="center" yoffset="0" color="#0A0A0A" />
    </frame>

    <!--
      Frame used for a header
    -->
    <frame name="header">
      <text font="header" hplacement="left" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <!--
      Frame used for a header
    -->
    <frame name="title">
      <text font="title" hplacement="left" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <!--
      Frame used for a progress bar
    -->
    <frame name="progress">
      <region source="controls" hplacement="left" vplacement="top" x="92" y="1" w="1" h="1" />
      <region source="controls" hplacement="stretch" vplacement="top" x="93" y="1" w="62" h="1" />
      <region source="controls" hplacement="right" vplacement="top" x="155" y="1" w="1" h="1" />
      <region source="controls" hplacement="left" vplacement="stretch" x="92" y="2" w="1" h="21" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="93" y="2" w="62" h="21" />
      <region source="controls" hplacement="right" vplacement="stretch" x="155" y="2" w="1" h="21" />
      <region source="controls" hplacement="left" vplacement="bottom" x="92" y="23" w="1" h="1" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="93" y="23" w="62" h="1" />
      <region source="controls" hplacement="right" vplacement="bottom" x="155" y="23" w="1" h="1" />
    </frame>

    <!--
      Frame used for a progress bar meter
    -->
    <frame name="progress.bar">
      <region source="controls" hplacement="left" vplacement="top" x="92" y="25" w="2" h="2" />
      <region source="controls" hplacement="stretch" vplacement="top" x="94" y="25" w="60" h="2" />
      <region source="controls" hplacement="right" vplacement="top" x="154" y="25" w="2" h="2" />
      <region source="controls" hplacement="left" vplacement="stretch" x="92" y="27" w="2" h="19" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="94" y="27" w="60" h="19" />
      <region source="controls" hplacement="right" vplacement="stretch" x="154" y="27" w="2" h="19" />
      <region source="controls" hplacement="left" vplacement="bottom" x="92" y="46" w="2" h="2" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="94" y="46" w="60" h="2" />
      <region source="controls" hplacement="right" vplacement="bottom" x="154" y="46" w="2" h="2" />
    </frame>

    <!--
      Frame used for a disabled pushbutton
    -->
    <frame name="button.disabled">
      <region source="controls" hplacement="left" vplacement="top" x="1" y="48" w="4" h="4" />
      <region source="controls" hplacement="stretch" vplacement="top" x="5" y="48" w="11" h="4" />
      <region source="controls" hplacement="right" vplacement="top" x="16" y="48" w="3" h="4" />
      <region source="controls" hplacement="left" vplacement="stretch" x="1" y="52" w="4" h="6" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="5" y="52" w="11" h="6" />
      <region source="controls" hplacement="right" vplacement="stretch" x="16" y="52" w="3" h="6" />
      <region source="controls" hplacement="left" vplacement="bottom" x="1" y="58" w="4" h="3" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="5" y="58" w="11" h="3" />
      <region source="controls" hplacement="right" vplacement="bottom" x="16" y="58" w="3" h="3" />
      <text font="default" hplacement="center" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <!--
      Frame used for a pushbutton in its normal state
    -->
    <frame name="button.normal">
      <region source="controls" hplacement="left" vplacement="top" x="1" y="62" w="4" h="4" />
      <region source="controls" hplacement="stretch" vplacement="top" x="5" y="62" w="11" h="4" />
      <region source="controls" hplacement="right" vplacement="top" x="16" y="62" w="3" h="4" />
      <region source="controls" hplacement="left" vplacement="stretch" x="1" y="66" w="4" h="6" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="5" y="66" w="11" h="6" />
      <region source="controls" hplacement="right" vplacement="stretch" x="16" y="66" w="3" h="6" />
      <region source="controls" hplacement="left" vplacement="bottom" x="1" y="72" w="4" h="3" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="5" y="72" w="11" h="3" />
      <region source="controls" hplacement="right" vplacement="bottom" x="16" y="72" w="3" h="3" />
      <text font="default" hplacement="center" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <!--
      Frame used for a pushbutton when it is highlighted
    -->
    <frame name="button.highlighted">
      <region source="controls" hplacement="left" vplacement="top" x="1" y="90" w="4" h="4" />
      <region source="controls" hplacement="stretch" vplacement="top" x="5" y="90" w="11" h="4" />
      <region source="controls" hplacement="right" vplacement="top" x="16" y="90" w="3" h="4" />
      <region source="controls" hplacement="left" vplacement="stretch" x="1" y="94" w="4" h="6" />
      <region source="controls" hplacement="stretch" vplacement="stretch" x="5" y="94" w="11" h="6" />
      <region source="controls" hplacement="right" vplacement="stretch" x="16" y="94" w="3" h="6" />
      <region source="controls" hplacement="left" vplacement="bottom" x="1" y="100" w="4" h="3" />
      <region source="controls" hplacement="stretch" vplacement="bottom" x="5" y="100" w="11" h="3" />
      <region source="controls" hplacement="right" vplacement="bottom" x="16" y="100" w="3" h="3" />
      <text font="default" hplacement="center" vplacement="center" yoffset="0" color="#3F3F3F" />
    </frame>

    <!--
      Frame used for a pushbutton when it is depressed
    -->
    <frame name="button.depressed">
      <region source="controls" hplacement="left" vplacement="top" x="1" y="76" w="4" h="4" />
      <region source="controls" hplacement="stretch" vplacement="top" x="5" y="76" w="11" h="4" />
